- id: interrogate
  name: interrogate
  description: "interrogate your code base for missing docstrings"
  entry: interrogate
  language: python
  language_version: python3
  types: [python]
  require_serial: true
  additional_dependencies: [setuptools]
