[build-system]
requires = ["setuptools>=80.9"]
build-backend = "setuptools.build_meta"

[project]
name = "interrogate"
version = "1.7.0"
description = "Interrogate a codebase for docstring coverage."
readme = {file = "README.rst", content-type = "text/x-rst"}
authors = [
    {name = "Lynn Root", email = "lynn@lynnroot.com"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
keywords = ["documentation", "coverage", "quality"]
dependencies = [
    "attrs",
    "click>=7.1",
    "colorama",
    "py",
    "tabulate",
    "tomli; python_version < '3.11'",
]

[project.urls]
Documentation = "https://interrogate.readthedocs.io"
"Bug Tracker" = "https://github.com/econchick/interrogate/issues"
"Source Code" = "https://github.com/econchick/interrogate"

[dependency-groups]
png = ["cairosvg"]
docs = ["sphinx", "sphinx-autobuild"]
tests = ["pytest", "pytest-cov", "pytest-mock", "coverage[toml]"]
typing = ["mypy", "types-tabulate"]
dev = [
    "cairosvg",
    "sphinx",
    "sphinx-autobuild",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "coverage[toml]",
    "mypy",
    "types-tabulate",
    "wheel",
    "pre-commit",
    "tox",
]

[project.scripts]
interrogate = "interrogate.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]
include = ["interrogate*"]

[tool.check-wheel-contents]
toplevel = ["interrogate"]


[tool.pytest.ini_options]
addopts = ["-ra", "--strict-markers", "--strict-config"]
testpaths = "tests"
xfail_strict = true

[tool.coverage.run]
parallel = true
branch = true
source = ["interrogate"]
omit = ["**/__main__.py"]

[tool.coverage.paths]
source = ["src", ".tox/py*/**/site-packages"]

[tool.coverage.report]
show_missing = true
exclude_lines = ["pragma: no cover"]
fail_under = 95

[tool.black]
line-length = 79

[tool.isort]
lines_after_imports=2
lines_between_types=1
known_first_party="interrogate"
known_third_party=["attr", "click", "py", "pytest", "setuptools", "tabulate"]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-module = false
ignore-property-decorators = false
fail-under = 95
exclude = ["tests/functional/sample", "setup.py", "docs"]
verbose = 0
omit-covered-files = false
quiet = false
whitelist-regex = []
ignore-regex = []
color = true

[tool.mypy]
strict = true
pretty = true
ignore_missing_imports = true
